title: elektrophon
author:
  name: spielhuus
  email: spielhus@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  analog and digital modules for an electroacustic instrument.

url: "https://spielhuus.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/elektrophon" # the subpath of your site, e.g. /blog

show_excerpts: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-assets

fixed_navbar: top
      
navigation:
  github: spielhuus/elektrophon
#  twitter: nakorndev
#  facebook: nakorndev
#  google: 113457032081840418568
  
sass:
  style: compact # possible values: nested expanded compact compressed


kramdown:
  hard_wrap: true
  syntax_highlighter: rouge

social_links:
  #twitter: jekyllrb
  github:  spielhuus
  # devto: jekyll
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll

      
############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: false

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  #tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  #locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################